import 'package:stockmeter/configurations/constants.dart';

class SheetData {
  static final String _fileTitle = StockConstants.fileName;
  static final String _fileVersion = '1.0.0';
  static final String _sheetStocks = 'stocks';

  String create() => '{"properties":{'
      '"title":"$_fileTitle"},'
      '"sheets":[${_data()}]}';

  String _data() => '{"data":['
      '${_rowData(0, 0, [
            'File generated by StockMeter app. Manual modifications on this sheet may provoke wrong behavior on the app.'
          ])},'
      '${_rowData(0, 7, [_fileVersion])},'
      '${_rowData(0, 19, [
            'Custom values displayed only when some value on them.'
          ])},'
      '${_rowData(1, 0, _sheetLabels())}'
      '],"properties":{"title":"$_sheetStocks"}}';

  String _rowData(int startRow, int startColumn, List<String> values) =>
      '{"rowData":${_values(values)},"startRow":$startRow,"startColumn":$startColumn}';

  String _values(List<String> values) =>
      '[{"values":[${values.map((value) => _value(value)).toList().join(',')}]}]';

  String _value(String value) =>
      '{"userEnteredValue":{"stringValue":"$value"}}';

  List<String> _sheetLabels() => [
        StockConstants.symbol,
        StockConstants.purchaseDate,
        StockConstants.stocks,
        StockConstants.purchasePrice,
        StockConstants.currency,
        'Commissions',
        StockConstants.tax,
        StockConstants.alertAbove,
        StockConstants.alertBelow,
        StockConstants.purchaseCapital,
        StockConstants.price,
        StockConstants.capitalValue,
        StockConstants.profit,
        StockConstants.grossGain,
        StockConstants.netGain,
        StockConstants.daysOld,
        StockConstants.profitDay,
        'Net Daily',
        'rowIndex',
        StockConstants.notes,
        'custom1',
        'custom2',
        'custom3'
      ];
}
